aspnet/WebSockets

build.cmd
build.sh
src/Microsoft.AspNet.WebSockets.Protocol/project.json
src/Microsoft.AspNet.WebSockets.Server/project.json
test/AutobahnTestClient/Project.json
test/AutobahnTestServer/Project.json
test/Microsoft.AspNet.WebSockets.Client.Test/project.json
test/Microsoft.AspNet.WebSockets.Protocol.Test/project.json
test/TestClient/project.json

Prepping to be merged once ready.

Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

---

src/Microsoft.AspNet.WebSockets.Protocol/project.json

Replace WebSocket dependency.

---

test/Microsoft.AspNet.WebSockets.Client.Test/KestrelWebSocketHelpers.cs

https://github.com/aspnet/Hosting/pull/237

React to WebHostingBuilder

---

test/Microsoft.AspNet.WebSockets.Protocol.Test/BufferStream.cs
test/Microsoft.AspNet.WebSockets.Protocol.Test/DuplexStream.cs
test/Microsoft.AspNet.WebSockets.Protocol.Test/project.json

Enable Microsoft.AspNet.WebSockets.Protocol.Test on CoreCLR.

---

test/Microsoft.AspNet.WebSockets.Client.Test/KestrelWebSocketHelpers.cs

Reach to Hosting changes

---

test/AutobahnTestServer/Project.json
test/AutobahnTestServer/Startup.cs
test/AutobahnTestServer/hosting.json
test/Microsoft.AspNet.WebSockets.Client.Test/KestrelWebSocketHelpers.cs

Reacting to https://github.com/aspnet/Hosting/pull/521

Reacting to new Hosting API

---

src/Microsoft.AspNet.WebSockets.Server/WebSocketMiddlewareExtensions.cs
test/AutobahnTestServer/Startup.cs

Standardizing ConfigureOptions to lambda https://github.com/aspnet/Coherence-Signed/issues/144

Stardardizing option initialization using lambdas

---

src/Microsoft.AspNet.WebSockets.Server/WebSocketMiddleware.cs
src/Microsoft.AspNet.WebSockets.Server/WebSocketMiddlewareExtensions.cs
src/Microsoft.AspNet.WebSockets.Server/WebSocketOptions.cs
src/Microsoft.AspNet.WebSockets.Server/project.json
test/AutobahnTestServer/Startup.cs

https://github.com/aspnet/Options/issues/105

Updating to new options pattern

---

NuGetPackageVerifier.json
src/Microsoft.AspNetCore.WebSockets.Client/project.json
src/Microsoft.AspNetCore.WebSockets.Protocol/project.json
src/Microsoft.AspNetCore.WebSockets.Server/project.json

Enabled xml doc generation

---

test/AutobahnTestClient/project.json
test/AutobahnTestServer/project.json
test/Microsoft.AspNetCore.WebSockets.Protocol.Test/BufferStream.cs
test/Microsoft.AspNetCore.WebSockets.Protocol.Test/DuplexStream.cs
test/Microsoft.AspNetCore.WebSockets.Protocol.Test/project.json
test/TestClient/project.json

Migrate tests/samples/tools to portable

---

test/AutobahnTestServer/project.json
test/Microsoft.AspNetCore.WebSockets.Client.Test/project.json
test/Microsoft.AspNetCore.WebSockets.Protocol.Test/project.json

Updating to RTM builds of xunit and Moq

---

WebSockets.sln
samples/EchoApp/project.json
src/Microsoft.AspNetCore.WebSockets/project.json
test/AutobahnTestApp/project.json
test/Microsoft.AspNetCore.WebSockets.Test/project.json

Fix #124 for 1.1 release.
/cc @muratg @Tratcher

update version to prepare for 1.1 release

---

src/Microsoft.AspNetCore.WebSockets/project.json

Added tags to project.json

---

scripts/UpdateCoreFxCode.ps1
src/Microsoft.AspNetCore.WebSockets/Internal/WebSocketFactory.cs
src/Microsoft.AspNetCore.WebSockets/Internal/fx/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs
src/Microsoft.AspNetCore.WebSockets/Internal/fx/src/Common/src/System/Net/WebSockets/WebSocketValidate.cs
src/Microsoft.AspNetCore.WebSockets/Microsoft.AspNetCore.WebSockets.csproj

Pulling in the latest code from CoreFX for `ManagedWebSocket`. Includes dotnet/corefx#17049 but also some older code that we haven't ported yet.
/cc @stephentoub

port dotnet/corefx#17049

---

appveyor.yml
test/Microsoft.AspNetCore.WebSockets.ConformanceTest/AutobahnTests.cs

fixes #152 
I also filed https://github.com/aspnet/AspNetCoreModule/issues/80 to track better conformance testing on the ANCM side.

suppress some Autobahn test failures

---

.gitignore
build/dependencies.props
samples/EchoApp/EchoApp.csproj
src/Microsoft.AspNetCore.WebSockets/Internal/fx/CompatHelpers.cs
src/Microsoft.AspNetCore.WebSockets/Microsoft.AspNetCore.WebSockets.csproj
test/AutobahnTestApp/AutobahnTestApp.csproj
test/Microsoft.AspNetCore.WebSockets.ConformanceTest/Autobahn/AutobahnTester.cs
test/Microsoft.AspNetCore.WebSockets.ConformanceTest/Microsoft.AspNetCore.WebSockets.ConformanceTest.csproj
test/Microsoft.AspNetCore.WebSockets.Test/Microsoft.AspNetCore.WebSockets.Test.csproj

* Remove net451 as a compilation target
* Upgrade to netcoreapp2.0

Change compilation targets.

---

test/Microsoft.AspNetCore.WebSockets.ConformanceTest/AutobahnTests.cs
test/Microsoft.AspNetCore.WebSockets.ConformanceTest/Helpers.cs
test/Microsoft.AspNetCore.WebSockets.ConformanceTest/Microsoft.AspNetCore.WebSockets.ConformanceTest.csproj

This PR removes all references to PlatformAbstractions.
Part of aspnet/PlatformAbstractions#50

react to removal of PlatformAbstractions

---

build/dependencies.props
src/Microsoft.AspNetCore.WebSockets/Microsoft.AspNetCore.WebSockets.csproj
test/Microsoft.AspNetCore.WebSockets.ConformanceTest/Microsoft.AspNetCore.WebSockets.ConformanceTest.csproj
test/Microsoft.AspNetCore.WebSockets.Test/Microsoft.AspNetCore.WebSockets.Test.csproj

https://github.com/aspnet/Coherence/issues/175

Remove unnecessary package references

---

test/AutobahnTestApp/Program.cs

- Introduced in https://github.com/aspnet/WebSockets/commit/79036ea166f4a1d1efa7ed7cf94fca8f017db4d5

Fix invalid format string

---

build/dependencies.props

upgrade deps to resolve build failures (#225)

---

test/Microsoft.AspNetCore.WebSockets.ConformanceTest/Autobahn/AutobahnTester.cs
test/Microsoft.AspNetCore.WebSockets.ConformanceTest/AutobahnTests.cs

Testing for instability x-plat
https://github.com/aspnet/Home/issues/2477

Re-enable SSL tests cross plat 

---

build/dependencies.props
test/Microsoft.AspNetCore.WebSockets.ConformanceTest/Autobahn/AutobahnTester.cs
test/Microsoft.AspNetCore.WebSockets.ConformanceTest/AutobahnTests.cs

React to IntegrationTesting changes

---

build/dependencies.props
src/Microsoft.AspNetCore.WebSockets/Microsoft.AspNetCore.WebSockets.csproj
src/Microsoft.AspNetCore.WebSockets/WebSocketMiddleware.cs
src/Microsoft.AspNetCore.WebSockets/WebSocketOptions.cs
src/Microsoft.AspNetCore.WebSockets/WebSocketsDependencyInjectionExtensions.cs
test/Microsoft.AspNetCore.WebSockets.Test/AddWebSocketsTests.cs
test/Microsoft.AspNetCore.WebSockets.Test/KestrelWebSocketHelpers.cs
test/Microsoft.AspNetCore.WebSockets.Test/WebSocketMiddlewareTests.cs

https://github.com/aspnet/Home/issues/2992
Ref: https://tools.ietf.org/html/rfc6455#section-10.2

Add Origin validation to WebSockets middleware
